fieldLayouts:
  238f1d6d-62ea-4af1-ac63-7c2b87493a92:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 60b734c9-66e9-4743-84a4-310f6f31036c
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 724bf21b-cea5-4e49-a9c9-da4f85771259
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 98fc5f43-3b8d-4818-8db4-37a6584aad92 # CTA Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5188a0f4-2305-4d6d-a11e-e5c2e648b820 # CTA Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 296b7b69-efdd-475f-a1b0-bdba61d58d49
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7c1b1669-fb76-4b7a-96c2-002b0a135163
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 36c09d73-9ed7-4f69-91f6-784ef5cf344f
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Homepage
        sortOrder: 1
      -
        elements:
          -
            fieldUid: f966a443-875a-400f-b52f-333459e33a04
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 516470f0-ea9a-4ece-8cde-9327ee5522dd
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: About
        sortOrder: 2
      -
        elements:
          -
            fieldUid: bb6d28f4-ee37-4fc6-8f63-be7c22f2831b
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3502cfad-f58c-4e50-88d3-b39d4f234517
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 10f9e12a-04f7-4984-a3f9-daaef315538e
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Members
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 35f147cd-67f9-4b1b-865b-e4d3feea6b2e
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4d1360d5-2fd6-42f4-8e9c-787bee78c4aa
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 06871b30-712c-4682-a5fd-8e8d347c2dc4
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b5a074a8-ff75-4632-98aa-62072a7d31df
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Music
        sortOrder: 4
handle: homepage
hasTitleField: false
name: Homepage
section: e830ad4a-dfeb-434a-b670-70ea190cf37c
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
