fieldLayouts:
  ee19bf45-337f-4bb6-b903-f484eb89d5df:
    tabs:
      -
        fields:
          16c3d7b5-9950-49bc-ad2b-ec1bb821012d:
            required: false
            sortOrder: 3
          99351592-5c9a-46b0-a45d-0e3a7fb57481:
            required: false
            sortOrder: 2
          ad88cb7b-e582-49f6-b554-ed29479ee830:
            required: false
            sortOrder: 1
        name: Songs
        sortOrder: 1
handle: songs
name: Songs
siteSettings:
  3c0b1454-ae0e-451e-b505-cf0eaea80e50:
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 2
  uid: aa8cf292-0a2d-4c84-a9d2-4b722b43b1c3
