fieldLayouts:
  b982361a-c8fa-4b56-b54b-6abd33dbdcb5:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: pdfs
hasUrls: false
name: PDFs
settings:
  path: /pdfs
sortOrder: 6
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: craft\volumes\Local
url: null
