contentColumnType: text
fieldGroup: 170555c3-76ee-4a23-ba64-9dc060c99120
handle: bandBio
instructions: ''
name: 'Band Bio'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '10'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
