contentColumnType: text
fieldGroup: 49d4bee5-cc40-4f27-9ec6-c89117ba0649
handle: bandHistory
instructions: ''
name: 'Band History'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  cleanupHtml: true
  columnType: text
  purifierConfig: ''
  purifyHtml: ''
  redactorConfig: Simple.json
  removeEmptyTags: '1'
  removeInlineStyles: ''
  removeNbsp: '1'
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
