contentColumnType: string
fieldGroup: 170555c3-76ee-4a23-ba64-9dc060c99120
handle: bandImages
instructions: ''
name: 'Band Images'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:d88670dc-ae7b-4fad-af62-fa47acfc3c48'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: ''
  singleUploadLocationSource: 'volume:b2fbd8ed-6e44-4ed2-8d57-07fbe9376496' # Band Members
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: ''
  validateRelatedElements: ''
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
