columnSuffix: null
contentColumnType: text
fieldGroup: 8f34b7f7-ccaf-4579-9b50-ed681ffe57ac # Blog
handle: blogText
instructions: ''
name: 'Blog Text'
searchable: true
settings:
  availableTransforms:
    - '2'
  availableVolumes:
    - '4'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: Standard.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
