columnSuffix: null
contentColumnType: string
fieldGroup: 8f34b7f7-ccaf-4579-9b50-ed681ffe57ac # Blog
handle: blogCategories
instructions: ''
name: 'Blog Categories'
searchable: true
settings:
  multi: true
  options:
    -
      __assoc__:
        -
          - label
          - Podcast
        -
          - value
          - podcast
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Freedom Rides'
        -
          - value
          - freedomRides
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Checkboxes
