contentColumnType: text
fieldGroup: 3c35caaf-7b3e-4240-8f80-01561ee1b5af
handle: blogAbstract
instructions: ''
name: 'Blog Abstract'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
