columnSuffix: null
contentColumnType: text
fieldGroup: 8f34b7f7-ccaf-4579-9b50-ed681ffe57ac # Blog
handle: blogHeader
instructions: ''
name: 'Blog Header'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
