columnSuffix: null
contentColumnType: text
fieldGroup: 8f34b7f7-ccaf-4579-9b50-ed681ffe57ac # Blog
handle: blogIntro
instructions: ''
name: 'Blog Intro'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
