contentColumnType: text
fieldGroup: 170555c3-76ee-4a23-ba64-9dc060c99120
handle: ctaUrl
instructions: ''
name: 'CTA Url'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
