columnSuffix: null
contentColumnType: string
fieldGroup: 435b0ef2-0c42-40bf-9055-6769daac4110 # Header
handle: heroImage
instructions: ''
name: 'Hero Image'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:2d5ef627-3d40-4895-8113-2ccae0a01303' # Hero Images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:2d5ef627-3d40-4895-8113-2ccae0a01303' # Hero Images
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
