contentColumnType: boolean
fieldGroup: 170555c3-76ee-4a23-ba64-9dc060c99120
handle: heroAnimated
instructions: ''
name: 'Hero Animated'
searchable: true
settings:
  default: '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
