columnSuffix: null
contentColumnType: text
fieldGroup: 435b0ef2-0c42-40bf-9055-6769daac4110 # Header
handle: heroHeader
instructions: ''
name: 'Hero Header'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
