columnSuffix: null
contentColumnType: text
fieldGroup: ad70e420-b63d-48b6-98a8-053806147750 # Social
handle: mapEmbedCode
instructions: ''
name: 'Map Embed Code'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
