contentColumnType: text
fieldGroup: 49d4bee5-cc40-4f27-9ec6-c89117ba0649
handle: memberBio
instructions: ''
name: 'Member Bio'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: 'Tell us a little bit about yourself...'
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
