contentColumnType: text
fieldGroup: 170555c3-76ee-4a23-ba64-9dc060c99120
handle: membersHeader
instructions: ''
name: 'Members Header'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
