contentColumnType: text
fieldGroup: 49d4bee5-cc40-4f27-9ec6-c89117ba0649
handle: memberLink
instructions: ''
name: 'Member Link'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: 'http://www.kurtcobain.com'
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
