columnSuffix: rqpdqvcx
contentColumnType: boolean
fieldGroup: 605f37ce-123b-46f5-9da2-fadf43eae62c # Pages
handle: navigation
instructions: null
name: Navigation
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
