contentColumnType: 'decimal(12,2)'
fieldGroup: 5585ab3c-7fe6-4ce4-8b79-68ae8c76f572
handle: showFee
instructions: ''
name: 'Show Fee'
searchable: true
settings:
  decimals: '2'
  defaultValue: null
  max: null
  min: '0'
  prefix: $
  size: null
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
