contentColumnType: datetime
fieldGroup: 5585ab3c-7fe6-4ce4-8b79-68ae8c76f572
handle: showDate
instructions: ''
name: 'Show Date'
searchable: true
settings:
  minuteIncrement: '15'
  showDate: true
  showTime: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
