contentColumnType: text
fieldGroup: 5585ab3c-7fe6-4ce4-8b79-68ae8c76f572
handle: showDetails
instructions: ''
name: 'Show Details'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
