columnSuffix: null
contentColumnType: text
fieldGroup: ad70e420-b63d-48b6-98a8-053806147750 # Social
handle: twitterUrl
instructions: ''
name: 'Twitter Url'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
