contentColumnType: integer(10)
fieldGroup: 5585ab3c-7fe6-4ce4-8b79-68ae8c76f572
handle: upcomingShowLimit
instructions: ''
name: 'Upcoming Show Limit'
searchable: false
settings:
  decimals: 0
  defaultValue: '10'
  max: null
  min: '0'
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
