contentColumnType: text
fieldGroup: 26d71486-d4bc-4845-ba36-080cec8e66c4
handle: youtubeVideoId
instructions: ''
name: 'YouTube Video Id'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
