comments:
  comments:
    fieldLayouts:
      3694d1a5-1034-4cb6-947d-977389795a15: null
dateModified: 1694571682
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - author
        - link
      type: native
    -
      heading: 'Web Pages'
      type: heading
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: singles
      tableAttributes:
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:acf24c93-7fa3-4a37-a4ae-cf8c9ab23097' # Pages
      tableAttributes:
        - 'field:74ecd784-b655-4dbd-8c83-09ed51bdfb92' # Navigation
        - dateUpdated
        - revisionCreator
        - link
      type: native
    -
      key: 'section:fa5a5a45-8f91-4811-87ca-f70f8c3c5774'
      type: native
    -
      heading: Components
      type: heading
    -
      key: 'section:ced25983-79ee-48f3-bb44-2ee772745cf7'
      type: native
    -
      key: 'section:7b556dc4-3462-4661-9940-e8be99cfa1f3'
      type: native
email:
  fromEmail: jack@jacksutherland.com
  fromName: 'Exit 85 CMS'
  replyToEmail: null
  template: ''
  transportSettings:
    command: ''
  transportType: craft\mail\transportadapters\Sendmail
fs:
  bandMembers:
    hasUrls: true
    name: 'Band Members'
    settings:
      path: files/members/images
    type: craft\fs\Local
    url: /files/members/images
  generic:
    hasUrls: true
    name: Generic
    settings:
      path: files/generic/images
    type: craft\fs\Local
    url: /files/generic/images
  songImages:
    hasUrls: true
    name: 'Song Images'
    settings:
      path: files/songs/images
    type: craft\fs\Local
    url: /files/songs/images
meta:
  __names__:
    1df98891-de4a-4f3b-9493-7aa7dd0b92d0: 'Band Members' # Band Members
    03c1d943-5731-4e0a-b4cd-c301940c61a1: Videos # Videos
    4a70f190-323c-4ef9-a0c7-d537fb6f9db3: Narrow # Narrow
    4c0ffcd0-7aa2-4454-a0f0-850267ca3e3e: 'CTA Entry' # CTA Entry
    4ed1bac7-17af-4f71-9961-8519c506f98c: Editors # Editors
    7f44c26b-1385-4e61-bae8-1066060c1b30: 'Song Images' # Song Images
    8bbaef41-5afc-491b-9f79-8158872c8402: Songs # Songs
    9f5b59a8-2c1c-4bbd-8b5a-86b6e643ccb3: 'Page Module' # Page Module
    35bf9abf-0692-4cbc-a674-75d0710b7d8b: 'Song Categories' # Song Categories
    65a77b75-6d41-4b63-b104-339c5672ef57: 'SEO Image' # SEO Image
    67cf4dbf-de4c-4ade-8f83-b158f47aac15: 'Headline & Text' # Headline & Text
    74ecd784-b655-4dbd-8c83-09ed51bdfb92: Navigation # Navigation
    75a11d67-2bb0-4101-93c2-45ece576ede7: Shows # Shows
    82b36c03-0800-4021-baf7-8150f571b0d7: 'Webpages Photo' # Webpages Photo
    97e24836-a4dd-4f62-a2af-07d6ea79b7b3: 'Webpages Photo Featured' # Webpages Photo Featured
    98fc5f43-3b8d-4818-8db4-37a6584aad92: 'CTA Text' # CTA Text
    411e1f23-44c6-4357-ba24-bba5636d8cc9: Alignment # Alignment
    605f37ce-123b-46f5-9da2-fadf43eae62c: Pages # Pages
    624d4b3b-cc7d-47b6-ba9d-e8fef7a1d84d: 'Webpages Song' # Webpages Song
    5188a0f4-2305-4d6d-a11e-e5c2e648b820: 'CTA Url' # CTA Url
    5039623b-4c9d-4bdc-affb-0dce5875e429: Photos # Photos
    11060338-318b-45f2-822c-89eb33731623: 'SEO Image' # SEO Image
    a0dea87c-86bb-41b0-be88-dd0eb63e619d: Headline # Headline
    a1f94466-082b-4389-b50a-6b1bf5a78021: Default # Default
    acf24c93-7fa3-4a37-a4ae-cf8c9ab23097: Pages # Pages
    b2fbd8ed-6e44-4ed2-8d57-07fbe9376496: 'Band Members' # Band Members
    b5df53a4-a5f2-40d3-affb-182a6be9069e: Headline # Headline
    b428df45-6612-4489-8dfe-b64da58cfcbb: 'Form Type' # Form Type
    c83ef70e-e3f7-4463-a97c-a1afba46695a: Video # Video
    c662e148-31bb-4faa-b17f-9f39f50d68b1: Photos # Photos
    cae0baae-3430-4f6a-8c5f-e3da61be0151: 'Rich Text' # Rich Text
    cb622695-130c-4061-9502-fc3c94d76cde: 'Show Types' # Show Types
    cff52376-83f8-4f48-ab5e-16825ee2d155: Form # Form
    d3ba0e91-b33f-4041-a7a7-0b24b31231f2: 'Mobile App' # Mobile App
    d8bc7357-d211-4b9c-8269-272ace2c5b1b: 'Old Homepage' # Old Homepage
    d88670dc-ae7b-4fad-af62-fa47acfc3c48: Generic # Generic
    e830ad4a-dfeb-434a-b670-70ea190cf37c: 'Old Homepage' # Old Homepage
    e491821d-19bf-4d23-a12e-9b3e596e8871: 'Show Media' # Show Media
    efd2d3da-b4e1-4583-8c18-73b4b145d86d: 'Song Image' # Song Image
    ffee4040-e5be-4518-8054-24387e9836fa: 'Band Image' # Band Image
plugins:
  comments:
    enabled: true
    licenseKey: U811NSF5PKID01Y0UKRDM4E6
    settings:
      allowAnonymous: null
      allowAnonymousFlagging: null
      allowAnonymousVoting: null
      allowFlagging: true
      allowGuest: false
      allowGuestFlagging: false
      allowGuestVoting: false
      allowVoting: true
      autoCloseDays: ''
      closed: null
      defaultQueryStatus:
        - approved
      downvoteCommentLimit: 5
      enableGravatar: false
      enableSpamChecks: true
      flaggedCommentLimit: 5
      guestNotice: ''
      guestRequireEmailName: true
      guestShowEmailName: true
      hideVotingForThreshold: false
      indexSidebarGroup: true
      indexSidebarIndividualElements: false
      indexSidebarLimit: 25
      maxReplyDepth: null
      maxUserComments: null
      moderatorUserGroup: null
      notificationAdminEnabled: false
      notificationAuthorEnabled: true
      notificationFlaggedEnabled: false
      notificationModeratorApprovedEnabled: false
      notificationModeratorEnabled: false
      notificationReplyEnabled: true
      notificationSubscribeAuto: false
      notificationSubscribeCommentEnabled: false
      notificationSubscribeDefault: true
      notificationSubscribeEnabled: false
      outputDefaultCss: true
      outputDefaultJs: true
      permissions: null
      placeholderAvatar: null
      recaptchaEnabled: false
      recaptchaKey: null
      recaptchaSecret: null
      requireModeration: true
      securityBanned: null
      securityFlooding: null
      securityMatchExact: false
      securityMaxLength: null
      securityModeration: null
      securitySpamlist: null
      showAvatar: true
      showCustomFieldInstructions: false
      showCustomFieldNames: false
      showTimeAgo: true
      structureUid: 6444bc69-6815-4afe-8223-3600c7713208
      templateEmail: null
      templateFolderOverride: null
      users: null
  mobile-detect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: pro
  live: true
  name: 'Exit 85'
  retryDuration: null
  schemaVersion: 4.5.0.3
  timeZone: America/New_York
