enableVersioning: true
handle: blogList
name: 'Blog List'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3c0b1454-ae0e-451e-b505-cf0eaea80e50:
    enabledByDefault: true
    hasUrls: true
    template: blog/_index
    uriFormat: blog
type: single
