defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  924e2a33-7a89-4e1a-b5d5-99b142c10e0b: # QC Family Tree
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
