defaultPlacement: end
enableVersioning: true
handle: homepage
name: 'Old Homepage'
propagationMethod: all
siteSettings:
  3c0b1454-ae0e-451e-b505-cf0eaea80e50:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
